"""Optimize Stage-1 dental/oral Gaussians on open-mouth dynamic poses.

This is the current UVD-FLAME counterpart of AnimPortrait3D/GSAvatar's
``train_mouth.py``.  It keeps the original ISM path as the default ablation,
optionally uses canonical UVD/CFD noise for a paired UVD-SFD score difference,
then runs the selected SDEdit phase.  It keeps the
reconstructed identity, topology and non-teeth Gaussians fixed, permits small
face-bounded UVD corrections on teeth, and exports a chained UVD PLY for
``train_full.py``.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from refinement_cli import (
    DEFAULT_SURFACE_SDEDIT_VIEWS,
    GUIDANCE_MODES,
    SDEDIT_MODES,
    guidance_mode_overrides,
    omega_override,
    output_overrides,
    refinement_run_name,
    require_stage1,
    resolve_path,
    run_launch,
    sdedit_mode_overrides,
)

ISM_STEPS = 500
MOUTH_PROMPT_PREFIX = "mouth region, "
DEFAULT_ANIMPORTRAIT3D_ROOT = Path(r"H:\work2\others\AnimPortrait3D")
DEFAULT_CONTROLNET = (
    DEFAULT_ANIMPORTRAIT3D_ROOT
    / "pretrained_model"
    / "AnimPortrait3D_controlnet"
)
DEFAULT_DIFFUSION = (
    DEFAULT_ANIMPORTRAIT3D_ROOT
    / "pretrained_model"
    / "Realistic_Vision_V5.1_noVAE"
)
DEFAULT_VAE = (
    DEFAULT_ANIMPORTRAIT3D_ROOT
    / "pretrained_model"
    / "sd-vae-ft-ema"
)
DEFAULT_CONDITION_ASSETS = (
    Path("ckpts") / "animportrait3d_normal_seg_flame_teeth"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--reconstruction",
        type=Path,
        default=Path("outputs/reconstruction/00000001"),
        help="Completed first-stage reconstruction directory",
    )
    parser.add_argument(
        "--prompt",
        default=None,
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help=(
            "Output directory (default: method-specific mouth or "
            "mouth_uvd_sfd directory)"
        ),
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=Path("configs/reconstruction_mouth.yaml"),
    )
    parser.add_argument(
        "--diffusion-path",
        type=Path,
        default=DEFAULT_DIFFUSION,
        help="AnimPortrait3D Realistic Vision no-VAE checkpoint",
    )
    parser.add_argument(
        "--vae-path",
        type=Path,
        default=DEFAULT_VAE,
        help="AnimPortrait3D sd-vae-ft-ema checkpoint",
    )
    parser.add_argument(
        "--controlnet-path",
        type=Path,
        default=DEFAULT_CONTROLNET,
        help="AnimPortrait3D 4-channel normal+seg ControlNet directory",
    )
    parser.add_argument(
        "--condition-assets",
        type=Path,
        default=DEFAULT_CONDITION_ASSETS,
        help=(
            "Current-topology verts_seg/face_region assets generated by "
            "tools/generate_animportrait3d_condition_assets.py"
        ),
    )
    parser.add_argument(
        "--guidance-mode",
        choices=GUIDANCE_MODES,
        default="ism",
        help=(
            "First phase: original AnimPortrait3D ISM or CFD-consistent "
            "UVD-SFD"
        ),
    )
    parser.add_argument(
        "--sdedit-mode",
        choices=SDEDIT_MODES,
        default="independent",
        help=(
            "Second-phase teacher; 'flame-surface' jointly denoises matched "
            "FLAME surface tokens across views"
        ),
    )
    parser.add_argument(
        "--surface-views",
        type=int,
        default=DEFAULT_SURFACE_SDEDIT_VIEWS,
        help="Joint views per FLAME surface-consistent SDEdit step",
    )
    parser.add_argument(
        "--uvd-ism-seed",
        "--uvd-flow-seed",
        dest="uvd_flow_seed",
        type=int,
        default=0,
        help="Canonical UVD noise seed; the old option name remains an alias",
    )
    parser.add_argument(
        "--max-steps",
        type=int,
        default=None,
        help=(
            "Override the total 500-guidance + 500-SDEdit steps; values <=500 "
            "run a first-phase-only smoke test"
        ),
    )
    parser.add_argument("--resume", type=Path, default=None)
    parser.add_argument("--gpu", default="0")
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def mouth_region_prompt(prompt: str) -> str:
    """Apply the regional prefix used verbatim by GSAvatar/train_mouth.py."""

    prompt = prompt.strip()
    if not prompt:
        raise ValueError("--prompt must not be empty")
    if prompt.casefold().startswith(MOUTH_PROMPT_PREFIX.casefold()):
        return prompt
    return MOUTH_PROMPT_PREFIX + prompt


def main() -> None:
    args = parse_args()
    reconstruction = resolve_path(args.reconstruction)
    require_stage1(reconstruction)
    output = (
        resolve_path(args.output)
        if args.output is not None
        else resolve_path(
            Path("outputs/refinement")
            / reconstruction.name
            / refinement_run_name(
                "mouth", args.guidance_mode, args.sdedit_mode
            )
        )
    )
    if (
        output.exists()
        and any(output.iterdir())
        and args.resume is None
        and not args.dry_run
    ):
        raise FileExistsError(
            f"Output directory is not empty: {output}. The repaired mouth "
            "topology must be trained in a fresh directory; pass --output "
            "with a new path (recommended) or --resume only for a checkpoint "
            "created by this implementation."
        )
    prompt = None
    if args.prompt is not None:
        prompt = mouth_region_prompt(args.prompt)

    controlnet = resolve_path(args.controlnet_path)
    controlnet_config = controlnet / "config.json"
    if not controlnet_config.is_file():
        raise FileNotFoundError(
            f"AnimPortrait3D ControlNet config does not exist: {controlnet_config}"
        )
    with controlnet_config.open("r", encoding="utf-8") as file:
        controlnet_metadata = json.load(file)
    conditioning_channels = int(
        controlnet_metadata.get("conditioning_channels", -1)
    )
    if conditioning_channels != 4:
        raise ValueError(
            "Mouth refinement requires AnimPortrait3D's 4-channel "
            f"normal+seg ControlNet, but {controlnet_config} declares "
            f"conditioning_channels={conditioning_channels}"
        )

    condition_assets = resolve_path(args.condition_assets)
    required_condition_assets = (
        "face_region_faces.npy",
        "face_region_verts_mask.npy",
        "verts_seg.npy",
        "verts_seg_idxs.json",
    )
    missing_condition_assets = [
        condition_assets / name
        for name in required_condition_assets
        if not (condition_assets / name).is_file()
    ]
    if missing_condition_assets:
        raise FileNotFoundError(
            "AnimPortrait3D condition assets are incomplete; missing: "
            + ", ".join(str(path) for path in missing_condition_assets)
        )

    overrides = output_overrides(output)
    overrides.extend(
        guidance_mode_overrides(
            args.guidance_mode,
            uvd_flow_seed=args.uvd_flow_seed,
        )
    )
    overrides.extend(
        sdedit_mode_overrides(
            args.sdedit_mode,
            surface_views=args.surface_views,
        )
    )
    overrides.extend(
        [
            omega_override("data.reconstruction_dir", reconstruction),
            omega_override("system.initialization_dir", reconstruction),
            omega_override("system.initialization_ply", ""),
            omega_override("system.initialization_params", ""),
            omega_override("system.optimization_stage", "mouth"),
            omega_override("data.condition_type", "animportrait3d_normal_seg"),
            omega_override("data.use_condition", True),
            omega_override("data.animportrait3d_assets_dir", condition_assets),
            omega_override("system.guidance.control_type", "animportrait3d"),
            omega_override(
                "system.guidance.pretrained_controlnet_name_or_path",
                controlnet,
            ),
            omega_override(
                "system.guidance.controlnet_conditioning_channels", 4
            ),
        ]
    )
    if prompt is not None:
        overrides.append(omega_override("system.prompt", prompt))
    diffusion = resolve_path(args.diffusion_path)
    required_diffusion_files = (
        diffusion / "model_index.json",
        diffusion / "unet" / "config.json",
        diffusion / "scheduler" / "scheduler_config.json",
    )
    missing_diffusion_files = [
        path for path in required_diffusion_files if not path.is_file()
    ]
    if missing_diffusion_files:
        raise FileNotFoundError(
            "AnimPortrait3D diffusion checkpoint is incomplete; missing: "
            + ", ".join(str(path) for path in missing_diffusion_files)
        )
    vae = resolve_path(args.vae_path)
    if not (vae / "config.json").is_file():
        raise FileNotFoundError(
            f"AnimPortrait3D VAE config does not exist: {vae / 'config.json'}"
        )
    overrides.extend(
        [
            omega_override(
                "system.guidance.pretrained_model_name_or_path", diffusion
            ),
            omega_override(
                "system.guidance.pretrained_vae_name_or_path", vae
            ),
            omega_override(
                "system.guidance.ddim_scheduler_name_or_path", diffusion
            ),
            omega_override(
                "system.prompt_processor.pretrained_model_name_or_path",
                diffusion,
            ),
        ]
    )
    if args.max_steps is not None:
        if args.max_steps <= 0:
            raise ValueError("--max-steps must be positive")
        if (
            args.sdedit_mode == "flame-surface"
            and args.max_steps <= ISM_STEPS
        ):
            raise ValueError(
                "--sdedit-mode flame-surface requires --max-steps to enter "
                f"the SDEdit phase (greater than {ISM_STEPS})"
            )
        ism_steps = min(args.max_steps, ISM_STEPS)
        schedule_end = max(ism_steps - 1, 1)
        overrides.extend(
            [
                omega_override("trainer.max_steps", args.max_steps),
                omega_override("system.optimization.max_steps", args.max_steps),
                "system.guidance.max_step_percent="
                f"[0,0.75,0.015,{schedule_end}]",
            ]
        )
        if args.max_steps <= ISM_STEPS:
            overrides.append(omega_override("system.sdedit.enabled", False))
    if args.resume is not None:
        resume = resolve_path(args.resume)
        if not resume.is_file():
            raise FileNotFoundError(f"Checkpoint does not exist: {resume}")
        overrides.append(omega_override("resume", resume))

    status = run_launch(args.config, args.gpu, overrides, args.dry_run)
    if status != 0:
        raise SystemExit(status)
    if not args.dry_run:
        print(f"Mouth refinement: {output / 'save' / 'mouth.ply'}")


if __name__ == "__main__":
    main()
